site_name: xOffFieldSoilRisk
site_url: ""
use_directory_urls: false
plugins:
  - search

repo_url: https://github.com/xlandscape/xOffFieldSoilRisk
repo_name: xOffFieldSoilRisk

theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/land-plots-marker
  favicon: img/land-plots-marker.svg
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Home: 'index.md'
  - Get Started: 'getstarted/getstarted.md'
  - Scenarios:
    - Scenario Intro: 'scenarios/intro-scenarios.md'
    - Scenario Development: 'scenarios/create-scenario.md'
    - Example Scenarios: 'scenarios/scenarios-examples.md'
  - Technical Reference:
    - Troubleshooting: 'reference/troubleshooting.md'
  - Glossary: 'reference/xOffFieldSoilRisk-glossary.md'
  - xLandscape:
    - Intro: 'xLandscape/xLandscape-intro.md'
    - Version 1.x: 'xLandscape/xLandscape-v1x.md'
    - Components: 'xLandscape/xLandscape-components.md'
    - Landscape Models: 'xLandscape/xLandscape-models.md'
    - Outlook: 'xLandscape/xLandscape-outlook.md'
    - Technology: 
      - Summary: 'xLandscape/xLandscape-technology.md'
      - Building Components: 'xLandscape/xLandscape-buildingComponents.md'
      - Building Landscape Models: 'xLandscape/xLandscape-buildingModels.md'
    - References: 'xLandscape/xLandscape-references.md'
    - Glossary: 'xLandscape/xLandscape-glossary.md'

    